// Autogenerated from csharp.template file

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

public class Car.cs {

    public int Prea {get; set;}
    public string Brand {get; set;}
    public string Model {get; set;}
    public string Engine {get; set;}
    public DateTime YearOfCreation {get; set;}

}