// Autogenerated from csharp.template file

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

public class GearBox.cs {

    public int ID {get; set;}
    public string Transmission {get; set;}

}